name: Build iOS App

on:
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      # 1) Use Python 3.10
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 2) Checkout
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 3) Install system deps & configure Git
      - name: Install system dependencies
        run: |
          brew update
          brew install git autoconf automake libtool pkg-config ios-deploy
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # 4) Create venv & install Buildozer/Cython
      - name: Create venv & install Buildozer
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install buildozer cython

      # 5) Manually clone mod-pbxproj & install
      - name: Manually clone pbxproj
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          source venv/bin/activate
          git clone https://$GITHUB_ACTOR:${GH_TOKEN}@github.com/kronenthaler/mod-pbxproj.git pbxproj_src
          pip install ./pbxproj_src

      # 6) Prepare Buildozer
      - name: Prepare Buildozer
        run: |
          source venv/bin/activate
          buildozer init
          # Force iOS in buildozer.spec
          sed -i '' 's/android/ios/' buildozer.spec
          sed -i '' 's/# requirements = python3,kivy/requirements = python3,kivy/' buildozer.spec
          # Add ios-deploy
          echo "ios.kivy_ios_deps = ios-deploy" >> buildozer.spec
          echo "ios.kivy_ios_reqs = ios-deploy" >> buildozer.spec
          # Force code signing off for debug
          sed -i '' 's/# ios.codesign.force = False/ios.codesign.force = True/' buildozer.spec
          sed -i '' 's/# ios.codesign.debug = True/ios.codesign.debug = False/' buildozer.spec
          # Only build current arch (arm64)
          echo "ios.xcodebuild.env = ONLY_ACTIVE_ARCH=YES" >> buildozer.spec

      # 7) Build .ipa, forcibly removing macOS references from ios-deploy
      - name: Build .ipa File
        run: |
          source venv/bin/activate

          # 7a) Let Buildozer fetch ios-deploy code
          buildozer ios update

          # 7b) Patch the ios-deploy.xcodeproj to remove x86_64 + macOS lines
          #     This is "nuclear" but ensures we only build arm64 for iOS.
          cd .buildozer/ios/platform/ios-deploy/ios-deploy.xcodeproj
          # Remove lines referencing macosx or x86_64
          sed -i '' '/macosx/d' project.pbxproj
          sed -i '' '/x86_64/d' project.pbxproj
          sed -i '' 's/MACOSX_DEPLOYMENT_TARGET = 10.8;/IPHONEOS_DEPLOYMENT_TARGET = 14.0;/g' project.pbxproj
          sed -i '' 's/MACOSX_DEPLOYMENT_TARGET = 10.11;/IPHONEOS_DEPLOYMENT_TARGET = 14.0;/g' project.pbxproj
          cd -

          # 7c) Now do the full build
          buildozer --log-level=2 -v ios debug

      # 8) Upload .ipa
      - name: Upload .ipa
        uses: actions/upload-artifact@v4
        with:
          name: ToDoApp.ipa
          path: bin/
