name: Build iOS App

on:
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      # 1) Set up Python 3.10 (avoids missing distutils issues with Python 3.12+)
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 2) Check out your repository code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 3) Install system dependencies via Homebrew
      - name: Install system dependencies
        run: |
          brew update
          brew install autoconf automake libtool pkg-config

      # 4) Create a venv and install Buildozer + "pbxproj" from GitHub
      - name: Create a Python venv and install Buildozer + pbxproj
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          # Install Buildozer & Cython from PyPI
          pip install buildozer cython
          # Install pbxproj from GitHub (since PyPI doesn't have an ARM64 wheel)
          pip install git+https://github.com/kronenthaler/python-pbxproj.git@master

      # 5) Prepare Buildozer (Optional: tweak buildozer.spec)
      - name: Prepare Buildozer
        run: |
          source venv/bin/activate
          buildozer init
          # Example: Force target iOS & basic requirements in buildozer.spec
          sed -i '' 's/android/ios/' buildozer.spec
          sed -i '' 's/# requirements = python3,kivy/requirements = python3,kivy/' buildozer.spec

      # 6) Build the .ipa file
      - name: Build .ipa File
        run: |
          source venv/bin/activate
          buildozer --log-level=2 -v ios debug

      # 7) Upload the .ipa artifact to GitHub Actions
      - name: Upload .ipa
        uses: actions/upload-artifact@v4
        with:
          name: ToDoApp.ipa
          path: bin/
