name: Build iOS App

on:
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          brew update
          brew install autoconf automake libtool pkg-config

      - name: Create a Python venv and install Buildozer + pbxproj
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          # Install Buildozer, Cython, and python-pbxproj
          pip install buildozer cython python-pbxproj

      - name: Prepare Buildozer
        run: |
          source venv/bin/activate
          buildozer init
          sed -i '' 's/android/ios/' buildozer.spec
          sed -i '' 's/# requirements = python3,kivy/requirements = python3,kivy/' buildozer.spec

      - name: Build .ipa File
        run: |
          source venv/bin/activate
          buildozer --log-level=2 -v ios debug  # For detailed logs

      - name: Upload .ipa
        uses: actions/upload-artifact@v4
        with:
          name: ToDoApp.ipa
          path: bin/
