name: Build iOS App

on:
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install system dependencies & configure Git
        run: |
          brew update
          brew install git autoconf automake libtool pkg-config
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create venv & install Buildozer
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install buildozer cython

      # 🔥 Remove trailing slash from .git
      - name: Manually clone pbxproj
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          source venv/bin/activate
          # Use the correct URL (no slash) and GitHub Actions token
          git clone https://$GITHUB_ACTOR:${GH_TOKEN}@github.com/kronenthaler/python-pbxproj.git pbxproj_src
          pip install ./pbxproj_src

      - name: Prepare Buildozer
        run: |
          source venv/bin/activate
          buildozer init
          sed -i '' 's/android/ios/' buildozer.spec
          sed -i '' 's/# requirements = python3,kivy/requirements = python3,kivy/' buildozer.spec

      - name: Build .ipa File
        run: |
          source venv/bin/activate
          buildozer --log-level=2 -v ios debug

      - name: Upload .ipa
        uses: actions/upload-artifact@v4
        with:
          name: ToDoApp.ipa
          path: bin/
