name: Build iOS App

on:
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      # 1) Use Python 3.10
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 2) Check out your repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 3) Install system dependencies & configure Git
      - name: Install system dependencies
        run: |
          brew update
          brew install git autoconf automake libtool pkg-config ios-deploy
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # 4) Create a venv & install Buildozer/Cython
      - name: Create venv & install Buildozer
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install buildozer cython

      # 5) Clone mod-pbxproj & install locally
      - name: Manually clone pbxproj
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          source venv/bin/activate
          git clone https://$GITHUB_ACTOR:${GH_TOKEN}@github.com/kronenthaler/mod-pbxproj.git pbxproj_src
          pip install ./pbxproj_src

      # 6) Prepare Buildozer (.spec tweaks)
      - name: Prepare Buildozer
        run: |
          source venv/bin/activate
          buildozer init
          # Force iOS in .spec & add basic requirements
          sed -i '' 's/android/ios/' buildozer.spec
          sed -i '' 's/# requirements = python3,kivy/requirements = python3,kivy/' buildozer.spec
          # Add ios-deploy
          echo "ios.kivy_ios_deps = ios-deploy" >> buildozer.spec
          echo "ios.kivy_ios_reqs = ios-deploy" >> buildozer.spec
          # Force code-signing off for debug
          sed -i '' 's/# ios.codesign.force = False/ios.codesign.force = True/' buildozer.spec
          sed -i '' 's/# ios.codesign.debug = True/ios.codesign.debug = False/' buildozer.spec
          # Also set an environment variable to avoid building x86_64 slices
          echo "ios.xcodebuild.env = ONLY_ACTIVE_ARCH=YES" >> buildozer.spec

      # 7) Build .ipa File with Xcode patch
      - name: Build .ipa File
        run: |
          source venv/bin/activate
          # 7a) Let Buildozer pull ios-deploy code once, so we can patch it
          buildozer ios update
          # 7b) Patch macOS deployment target in ios-deploy.xcodeproj
          sed -i '' 's/MACOSX_DEPLOYMENT_TARGET = 10.11;/MACOSX_DEPLOYMENT_TARGET = 10.13;/' \
            .buildozer/ios/platform/ios-deploy/ios-deploy.xcodeproj/project.pbxproj
          # 7c) Now do the full build
          buildozer --log-level=2 -v ios debug

      # 8) Upload .ipa
      - name: Upload .ipa
        uses: actions/upload-artifact@v4
        with:
          name: ToDoApp.ipa
          path: bin/
