name: Build iOS App

on:
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      # 1) Set up Python 3.10
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 2) Check out your repository code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 3) Install system dependencies & configure Git
      - name: Install system dependencies
        run: |
          brew update
          brew install git autoconf automake libtool pkg-config
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # 4) Create a virtual env, install Buildozer & Cython
      - name: Create venv & install Buildozer
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install buildozer cython

      # 5) Clone pbxproj with GitHub Actions token & install from local
      #    This avoids 'fatal: could not read Username' for public repos on some runners
      - name: Manually clone pbxproj
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          source venv/bin/activate
          git clone https://$GITHUB_ACTOR:${GH_TOKEN}@github.com/kronenthaler/python-pbxproj.git pbxproj_src
          pip install ./pbxproj_src

      # 6) Prepare Buildozer (example tweak buildozer.spec)
      - name: Prepare Buildozer
        run: |
          source venv/bin/activate
          buildozer init
          # Force iOS in .spec & add Kivy
          sed -i '' 's/android/ios/' buildozer.spec
          sed -i '' 's/# requirements = python3,kivy/requirements = python3,kivy/' buildozer.spec

      # 7) Build the .ipa file
      - name: Build .ipa File
        run: |
          source venv/bin/activate
          buildozer --log-level=2 -v ios debug

      # 8) Upload the .ipa artifact
      - name: Upload .ipa
        uses: actions/upload-artifact@v4
        with:
          name: ToDoApp.ipa
          path: bin/
